# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name_plural': 'Stations'},
        ),
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
