# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colector', '0003_auto_20200408_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_request', models.DateTimeField(auto_now=True)),
                ('new_config', models.BooleanField(default=False)),
                ('info', models.CharField(max_length=128)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colector.Station')),
            ],
        ),
    ]
