# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colector', '0006_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='station',
        ),
        migrations.DeleteModel(
            name='emails',
        ),
    ]
