# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colector', '0009_auto_20200619_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colector.Station'),
        ),
    ]
